server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Ankit@123
    url: jdbc:mysql://localhost:3306/sbms
    username: ankitdb
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    password: pwd
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ankitrajj95@gmail.com
reg-app: 
  messages:
    regMailSubject: User Registration Success
    regMailBodyTemplateFile: UNLOCK-ACC-EMAIL-BODY-TEMPLATE.txt
